[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
botanika_solana_rewards_distributor = "GPk4SPDWTZyNDHDc7E37qzGLiWFAoF3Q94Uvzp1rRZbB"

[programs.localnet]
botanika_solana_rewards_distributor = "EgXM56PxY7JNSDwwBu2S4LXQV8JMJaJcQq2KTJzg5RQg"

[programs.testnet]
botanika_solana_rewards_distributor = "rwW2u8xGwcWHAiuFTnEPyyFmvP7X4e8B75arewK4qQS"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/botanika-solana-rewards-distributor/Cargo.toml"