[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
botanika_solana_rewards_distributor = "J9gu41htkjXKAJxrmEfciYDPxPdP7xg8BV7sgNtaXdZs"

[programs.localnet]
botanika_solana_rewards_distributor = "EgXM56PxY7JNSDwwBu2S4LXQV8JMJaJcQq2KTJzg5RQg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/botanika-solana-rewards-distributor/Cargo.toml"
